version: "3"
services:
  install:
    user: node
    image: node:18
    volumes:
      - .:/app
    command: bash -c "cd /app && rm -rf node_modules && rm -f package-lock.json && npm i"  
  installTest:
    user: node
    image: node:18
    volumes:
      - .:/app
    command: bash -c "cd /app/test && rm -rf node_modules && rm -f package-lock.json && npm i"
  build: 
    user: node
    image: node:18
    volumes:
      - .:/app
    command: bash -c "cd /app && npm run build"     
  buildTest: 
    user: node
    image: node:18
    volumes:
      - .:/app
    command: bash -c "cd /app/test && npm run build"  
  test:
    user: node
    image: node:18
    ports:
      - "8085:8080"
    volumes:
      - .:/app
    command: bash -c "cd /app/test && npm run test"   